# integrations/qbo_invoice_client.py
# AgAI_27 - Quote-to-Invoice Platform
#
# Handles the AR (outbound) direction:
#   Approved quote -> QuickBooks customer Invoice
#
# This is separate from quickbooks_client.py which handles AP (inbound Bills).
# Key differences:
#   - QBO object: Invoice (not Bill)
#   - Customer lookup (not Vendor)
#   - User-facing OAuth2 flow with redirect URI
#   - Data source: quote configurator output (not extracted PDF)

from __future__ import annotations

import base64
import json
from datetime import datetime
from decimal import Decimal
from typing import Optional

import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

from core.config import get_settings
from core.logger import get_logger
from core.models import Quote, QBOInvoiceSyncResult

logger = get_logger(__name__)
settings = get_settings()

QBO_BASE_URL        = "https://quickbooks.api.intuit.com/v3/company"
QBO_SANDBOX_BASE    = "https://sandbox-quickbooks.api.intuit.com/v3/company"
QBO_TOKEN_URL       = "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"
QBO_AUTH_URL        = "https://appcenter.intuit.com/connect/oauth2"
QBO_REVOKE_URL      = "https://developer.api.intuit.com/v2/oauth2/tokens/revoke"


class QBOAuthError(Exception):
    pass


class QBOInvoiceError(Exception):
    pass


# ─── URL helpers ─────────────────────────────────────────────────────────────

def _get_base_url() -> str:
    if settings.app_env == "production":
        return f"{QBO_BASE_URL}/{settings.quickbooks_realm_id}"
    return f"{QBO_SANDBOX_BASE}/{settings.quickbooks_realm_id}"


def _get_headers(access_token: str) -> dict:
    return {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }


def _basic_auth_header() -> str:
    credentials = base64.b64encode(
        f"{settings.quickbooks_client_id}:{settings.quickbooks_client_secret}".encode()
    ).decode()
    return f"Basic {credentials}"


# ─── OAuth2 flow (user-facing) ───────────────────────────────────────────────

def build_authorization_url(state: str) -> str:
    """
    Build the QBO OAuth2 authorization URL to redirect the user to.
    `state` is a signed JWT generated by the auth router to prevent CSRF.

    Returns the full redirect URL string.
    """
    import urllib.parse
    params = {
        "client_id":     settings.quickbooks_client_id,
        "redirect_uri":  settings.quickbooks_redirect_uri,
        "response_type": "code",
        "scope":         "com.intuit.quickbooks.accounting",
        "state":         state,
    }
    return f"{QBO_AUTH_URL}?{urllib.parse.urlencode(params)}"


def exchange_code_for_tokens(code: str) -> dict:
    """
    Exchange the authorization code (from QBO callback) for access + refresh tokens.
    Returns dict with: access_token, refresh_token, realm_id, expires_in.
    """
    try:
        response = httpx.post(
            QBO_TOKEN_URL,
            headers={
                "Authorization": _basic_auth_header(),
                "Content-Type": "application/x-www-form-urlencoded",
            },
            data={
                "grant_type":   "authorization_code",
                "code":         code,
                "redirect_uri": settings.quickbooks_redirect_uri,
            },
            timeout=15,
        )
        response.raise_for_status()
        data = response.json()

        if "access_token" not in data:
            raise QBOAuthError(f"No access_token in response: {data}")

        logger.info("qbo_tokens_exchanged", expires_in=data.get("expires_in"))
        return data

    except httpx.HTTPStatusError as exc:
        logger.error("qbo_code_exchange_failed", error=exc.response.text[:500])
        raise QBOAuthError(f"Code exchange failed: {exc}")


def refresh_access_token(refresh_token: Optional[str] = None) -> str:
    """
    Refresh the QBO access token using the stored or provided refresh token.
    Returns a fresh access token string.
    """
    token = refresh_token or settings.quickbooks_refresh_token

    if not token:
        raise QBOAuthError("No refresh token available. Run the OAuth2 flow first.")

    try:
        response = httpx.post(
            QBO_TOKEN_URL,
            headers={
                "Authorization": _basic_auth_header(),
                "Content-Type": "application/x-www-form-urlencoded",
            },
            data={
                "grant_type":    "refresh_token",
                "refresh_token": token,
            },
            timeout=15,
        )
        response.raise_for_status()
        data = response.json()
        access_token = data.get("access_token")

        if not access_token:
            raise QBOAuthError("No access_token in refresh response.")

        logger.info("qbo_token_refreshed")
        return access_token

    except httpx.HTTPStatusError as exc:
        logger.error("qbo_token_refresh_failed", error=exc.response.text[:500])
        raise QBOAuthError(f"Token refresh failed: {exc}")


# ─── Customer operations ─────────────────────────────────────────────────────

@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10))
def find_or_create_customer(
    client_name: str,
    contact_email: Optional[str] = None,
    access_token: Optional[str] = None,
) -> dict:
    """
    Find an existing QBO Customer by display name, or create a new one.
    Returns the QBO Customer object.
    """
    token = access_token or refresh_access_token()
    base_url = _get_base_url()
    headers = _get_headers(token)

    # Search for existing customer
    try:
        query = f"SELECT * FROM Customer WHERE DisplayName = '{client_name}'"
        response = httpx.get(
            f"{base_url}/query",
            headers=headers,
            params={"query": query},
            timeout=15,
        )
        response.raise_for_status()
        customers = response.json().get("QueryResponse", {}).get("Customer", [])

        if customers:
            logger.info(
                "qbo_customer_found",
                client_name=client_name,
                qbo_id=customers[0].get("Id"),
            )
            return customers[0]

    except Exception as exc:
        logger.warning("qbo_customer_search_failed", client_name=client_name, error=str(exc))

    # Create new customer
    customer_payload: dict = {
        "DisplayName": client_name,
        "PrintOnCheckName": client_name,
        "CompanyName": client_name,
    }
    if contact_email:
        customer_payload["PrimaryEmailAddr"] = {"Address": contact_email}

    try:
        response = httpx.post(
            f"{base_url}/customer",
            headers=headers,
            json=customer_payload,
            timeout=15,
        )
        response.raise_for_status()
        customer = response.json().get("Customer", {})

        logger.info(
            "qbo_customer_created",
            client_name=client_name,
            qbo_id=customer.get("Id"),
        )
        return customer

    except httpx.HTTPStatusError as exc:
        logger.error("qbo_customer_create_failed", client_name=client_name, error=exc.response.text[:500])
        raise QBOInvoiceError(f"Customer creation failed: {exc}")


# ─── Invoice payload builder ─────────────────────────────────────────────────

def _build_qbo_invoice_payload(quote: Quote, customer_ref: dict) -> dict:
    """
    Map a Quote model to the QBO Invoice payload format.
    QBO Invoice is the AR object (customer owes us money).
    """
    lines = []

    if quote.line_items:
        for item in quote.line_items:
            lines.append({
                "Amount": float(item.total),
                "DetailType": "SalesItemLineDetail",
                "Description": f"{item.category}: {item.description}",
                "SalesItemLineDetail": {
                    "ItemRef": {
                        "value": "1",       # Default "Services" item in QBO
                        "name": "Services",
                    },
                    "Qty": float(item.quantity),
                    "UnitPrice": float(item.unit_price),
                },
            })
    else:
        lines.append({
            "Amount": float(quote.total),
            "DetailType": "SalesItemLineDetail",
            "Description": f"Quote {quote.quote_number}",
            "SalesItemLineDetail": {
                "ItemRef": {"value": "1", "name": "Services"},
                "Qty": 1,
                "UnitPrice": float(quote.total),
            },
        })

    payload = {
        "CustomerRef": {
            "value": customer_ref.get("Id"),
            "name": customer_ref.get("DisplayName"),
        },
        "DocNumber": quote.quote_number,
        "TxnDate": str(datetime.utcnow().date()),
        "CurrencyRef": {"value": quote.currency},
        "TotalAmt": float(quote.total),
        "Line": lines,
        "PrivateNote": f"Created by AgAI_27. Quote: {quote.quote_number}",
    }

    if quote.notes:
        payload["CustomerMemo"] = {"value": quote.notes}

    return payload


# ─── Invoice creation ────────────────────────────────────────────────────────

@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10))
def create_invoice_in_qbo(
    quote: Quote,
    access_token: Optional[str] = None,
) -> QBOInvoiceSyncResult:
    """
    Create a customer Invoice in QuickBooks Online from an approved Quote.
    Finds or creates the QBO customer automatically.
    Returns a QBOInvoiceSyncResult.
    """
    if not settings.quickbooks_realm_id:
        raise QBOInvoiceError("QUICKBOOKS_REALM_ID is not configured.")

    token = access_token or refresh_access_token()
    base_url = _get_base_url()
    headers = _get_headers(token)

    client_name  = quote.client.client_name
    contact_email = quote.client.contact_email

    # Find or create customer
    customer_ref = find_or_create_customer(client_name, contact_email, token)

    # Build and post the invoice
    payload = _build_qbo_invoice_payload(quote, customer_ref)

    try:
        response = httpx.post(
            f"{base_url}/invoice",
            headers=headers,
            json=payload,
            timeout=20,
        )
        response.raise_for_status()
        invoice = response.json().get("Invoice", {})
        qbo_invoice_id     = invoice.get("Id")
        qbo_invoice_number = invoice.get("DocNumber")

        logger.info(
            "qbo_invoice_created",
            quote_number=quote.quote_number,
            qbo_invoice_id=qbo_invoice_id,
            qbo_invoice_number=qbo_invoice_number,
            total=str(quote.total),
        )

        return QBOInvoiceSyncResult(
            quote_number=quote.quote_number,
            success=True,
            qbo_invoice_id=qbo_invoice_id,
            qbo_invoice_number=qbo_invoice_number,
        )

    except httpx.HTTPStatusError as exc:
        error_msg = exc.response.text[:500]
        logger.error(
            "qbo_invoice_create_failed",
            quote_number=quote.quote_number,
            status=exc.response.status_code,
            error=error_msg,
        )
        return QBOInvoiceSyncResult(
            quote_number=quote.quote_number,
            success=False,
            error_message=error_msg,
        )


# ─── Health check ────────────────────────────────────────────────────────────

def check_qbo_connection() -> bool:
    """
    Verify QBO connectivity by fetching company info.
    Returns True if connected, False otherwise.
    """
    try:
        token = refresh_access_token()
        base_url = _get_base_url()
        headers = _get_headers(token)

        response = httpx.get(
            f"{base_url}/companyinfo/{settings.quickbooks_realm_id}",
            headers=headers,
            timeout=10,
        )
        response.raise_for_status()
        company = response.json().get("CompanyInfo", {})
        logger.info("qbo_connection_verified", company=company.get("CompanyName"))
        return True

    except Exception as exc:
        logger.error("qbo_connection_failed", error=str(exc))
        return False
